name: Build Windows EXE & Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Build single-file EXE
        run: |
          pyinstaller --onefile --windowed ^
            --add-data "creds.json;." ^
            --add-data "images;images" ^
            main.py

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Compile Windows Installer
        run: |
          &"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: WhatsAppBatchSender
          path: |
            dist/WhatsAppBatchSender.exe
            WhatsAppBatchSenderSetup.exe
